// Constants

export const LANGUAGES = {
  English: "en",
  Spanish: "es",
  French: "fr",
  German: "de",
  Italian: "it",
  Portuguese: "pt",
  Russian: "ru",
  Japanese: "ja",
  Korean: "ko",
  Chinese: "zh",
  Hindi: "hi",
  Arabic: "ar",
  Turkish: "tr",
  Persian: "fa",
  Polish: "pl",
  Dutch: "nl",
  Swedish: "sv",
  Norwegian: "no",
  Danish: "da",
  Finnish: "fi",
  Greek: "el",
  Hebrew: "he",
  Thai: "th",
  Vietnamese: "vi",
  Indonesian: "id",
  Ukrainian: "uk",
  Hungarian: "hu",
  Czech: "cs",
  Romanian: "ro",
  Bulgarian: "bg",
  Serbian: "sr",
  Slovak: "sk",
  Slovenian: "sl",
  Estonian: "et",
  Latvian: "lv",
  Lithuanian: "lt",
  Georgian: "ka",
  Armenian: "hy",
};

export const COUNTRIES = {
  USA: "US",
  UK: "GB",
  Canada: "CA",
  France: "FR",
  Germany: "DE",
  Italy: "IT",
  Spain: "ES",
  Portugal: "PT",
  Russia: "RU",
  Japan: "JP",
  SouthKorea: "KR",
  China: "CN",
  India: "IN",
  Iran: "IR",
  Turkey: "TR",
  Brazil: "BR",
  Mexico: "MX",
  Argentina: "AR",
  Australia: "AU",
  NewZealand: "NZ",
  Sweden: "SE",
  Norway: "NO",
  Denmark: "DK",
  Finland: "FI",
  Netherlands: "NL",
  Belgium: "BE",
  Switzerland: "CH",
  Austria: "AT",
  Poland: "PL",
  Ukraine: "UA",
  Romania: "RO",
  Bulgaria: "BG",
  Greece: "GR",
  Israel: "IL",
  Egypt: "EG",
  SouthAfrica: "ZA",
  Armenia: "AM",
  Georgia: "GE",
};

export const GENRES = {
  Action: 28,
  Adventure: 12,
  Animation: 16,
  Comedy: 35,
  Crime: 80,
  Documentary: 99,
  Drama: 18,
  Family: 10751,
  Fantasy: 14,
  History: 36,
  Horror: 27,
  Music: 10402,
  Mystery: 9648,
  Romance: 10749,
  "Science Fiction": 878,
  "TV Movie": 10770,
  Thriller: 53,
  War: 10752,
  Western: 37,
};

export const RELEASE_TYPES = {
  Premiere: 1,
  "Theatrical (limited)": 2,
  Theatrical: 3,
  Digital: 4,
  Physical: 5,
  TV: 6,
};

export const KEYWORDS = {
  superhero: 9715,
  "based on novel": 818,
  sequel: 523,
  prequel: 414,
  remake: 968,
  reboot: 9748,
  friendship: 6054,
  love: 9840,
  revenge: 9748,
  betrayal: 6054,
  "time travel": 4379,
  dystopia: 4565,
  post_apocalyptic: 4458,
  future: 9831,
  war: 1956,
  military: 4165,
  politics: 6054,
  biography: 9672,
  true_story: 9672,
  sports: 180547,
  "martial arts": 779,
  boxing: 9743,
  zombie: 12377,
  vampire: 3133,
  alien: 9951,
  monster: 947,
  anime: 210024,
  "based on manga": 206563,
  "based on comic": 9715,
  heist: 10349,
  spy: 470,
  detective: 703,
};

export const SORT_MAPPING = {
  "Popularity Ascending": "popularity.asc",
  "Popularity Descending": "popularity.desc",
  "Rating Ascending": "vote_average.asc",
  "Rating Descending": "vote_average.desc",
  "Release Date Ascending": "primary_release_date.asc",
  "Release Date Descending": "primary_release_date.desc",
  "A-Z": "title.asc",
  "Z-A": "title.desc",
};

export const API_KEY = "2de47dd8b744f69009564aec2ad06d07";
